#!/bin/bash

if ! service mongod status | grep "running"; then
	echo "No mongodb server running..."
	read -n1 -p "Should I start it for you using sudo start service mongod?(y/n)" answer
	echo
	case $answer in
	    y|Y) sudo service mongod start ;;
	    *) echo "Exiting..." ;
	        exit ;;
	esac
fi


echo "populating database from git dumps..."

declare -a arr=("kavita" "dohe" "kahani" "muhavare" "dictionary")

for i in "${arr[@]}"
do
	echo "populating $i"
	mongorestore -d "literature" -c $i "dump/literature/$i.bson"
done
