#!/bin/bash
if ! service mongod status | grep "running"; then
	echo "No mongodb server running..."
	read -n1 -p "Should I start it for you using sudo start service mongod?(y/n)" answer
	echo
	case $answer in
	    y|Y) echo "Checking..."
             echo "you are on $(uname)"
             if [ "$(uname)" == "Darwin" ]; then
                sudo mongod
             else
                sudo service mongod start
             fi
             ;;
	    *) echo "Exiting..."
	        exit ;;
	esac
fi
export FLASK_DEBUG=1
export FLASK_APP=api/app.py
python -m flask run
