#!/bin/bash
declare -r mongoVersion=3.6.5
# above mongoVersion isn't really being used because
# it seems like the key is different for different versions
echo "checking dependencies..."

if ! mongod --version | grep "db version v$mongoVersion"; then
        echo "found no installation of mongodb, installing from repo..."
        read -n1 -p "Should I install mongodb?(y/n) (I assume ubuntu 16.04)" answer
        echo
        case $answer in
        y|Y) sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5;
        echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list;
        sudo apt-get update;
        sudo apt-get install -y mongodb-org=3.6.5 mongodb-org-server=3.6.5 mongodb-org-shell=3.6.5 mongodb-org-mongos=3.6.5 mongodb-org-tools=3.6.5
;;
        *) echo "Exiting ... " ;
        exit;;
        esac
fi

if ! pip3 --version | grep "(python 3."; then
        echo "found no installation of pip3, installing from repo..."
        sudo apt install python3-pip;
fi

if ! pipenv --version | grep "pipenv, version"; then
        echo "found no installation of pipenv installing..."
        pip install pipenv;
fi

if ! python3.6 --version | grep "Python 3.6."; then
        echo " found no python 3.6, installing..."
        sudo add-apt-repository ppa:jonathonf/python-3.6;
        sudo apt-get update;
        sudo apt-get install python3.6;
fi

if ! pip freeze | grep Flask; then
        echo "found no flask, installing flask..."
        pip install Flask;
fi
